---
sidebar: sidebar 
permalink: concept_backup_to_cloud.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, back up volumes, Backup to Cloud, restore volumes, billing, cost, on-premises ONTAP, onprem, restore files 
summary: クラウドへのバックアップは、 ONTAP クラスタとオンプレミス Cloud Volumes ONTAP クラスタに対応するアドオンサービスで、保護のためのバックアップとリストア機能を提供し、クラウドデータを長期にわたってアーカイブできる。バックアップは、短期リカバリやクローニングに使用されるボリューム Snapshot コピーとは無関係に、クラウドアカウントのオブジェクトストアに格納されます。 
---
= クラウドへのバックアップの詳細をご確認ください
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラウドへのバックアップは、 ONTAP クラスタとオンプレミス Cloud Volumes ONTAP クラスタに対応するアドオンサービスで、保護のためのバックアップとリストア機能を提供し、クラウドデータを長期にわたってアーカイブできる。バックアップは、短期リカバリやクローニングに使用されるボリューム Snapshot コピーとは無関係に、クラウドアカウントのオブジェクトストアに格納されます。

バックアップとリストアの機能をすべて備えた 2 つのサービスがあります。

* クラウドへのバックアップサービス * を使用すると、バックアップファイルを作成したり、ボリューム全体を同じ作業環境または異なる作業環境にリストアしたりできます。
* * Restore service * を使用すると、同じバックアップ・ファイルを使用して、同じ作業環境または異なる作業環境内のボリュームに 1 つ以上の * ファイル * をリストアできます。これは、単一ファイルのリストアとも呼ばれます。


クラウドへのバックアップには、が採用されています https://cloud.netapp.com/cloud-backup-service["Cloud Backup サービスの略"^]。


NOTE: すべてのバックアップ処理とリストア処理には、 Cloud Manager を使用する必要があります。ONTAP から直接、またはクラウドプロバイダから何らかの操作を実行すると、サポートされない構成になります。



== の機能

* データボリュームの独立したコピーをクラウド上の低コストのオブジェクトストレージにバックアップできます。
* バックアップデータは、転送中の AES-256 ビット暗号化と TLS 1.2 HTTPS 接続によって保護されます。
* クラウドからクラウドへ、オンプレミスの ONTAP システムからクラウドへバックアップできます。
* 単一ボリュームで最大 1 、 019 個のバックアップをサポート
* 特定の時点からデータをリストアします。
* ボリュームまたは個々のファイルをソースシステムまたは別のシステムにリストアする。
* 単一ファイルのリストアに使用できる参照可能なファイルカタログです。




== サポートされている作業環境とオブジェクトストレージプロバイダ

現時点で、 Backup to Cloud を使用すると、次の作業環境からボリュームのバックアップを作成できます。

[cols="50,40"]
|===
| ソースの作業環境 | バックアップファイルの保存先 


| AWS の Cloud Volumes ONTAP | Amazon S3 


| Azure の Cloud Volumes ONTAP | Azure Blob の略 


| Google の Cloud Volumes ONTAP | Google クラウドストレージ 


| オンプレミスの ONTAP システム | Amazon S3 Azure Blob 
|===
ボリュームまたは個々のファイルをバックアップファイルから次の作業環境にリストアできます。

[cols="30,40,40"]
|===
| バックアップファイルの場所 2+| 作業環境を復元します 


|  | * ボリュームの復元 * | * 単一ファイルの復元 * 


| Amazon S3 | AWS の Cloud Volumes ONTAP | オンプレミスの AWS ONTAP システムに Cloud Volumes ONTAP が導入されている 


| Azure Blob の略 | Azure の Cloud Volumes ONTAP | オンプレミスの Azure ONTAP システムに Cloud Volumes ONTAP を導入 


| Google クラウドストレージ | Google の Cloud Volumes ONTAP |  
|===


== コスト

Backup to Cloud の使用に関連するコストには、リソース料金とサービス料金の 2 種類があります。

* リソース料金 *

リソースの料金は、ストレージやクラウドで仮想マシン / インスタンスを実行するためにクラウドプロバイダに支払われます。

* バックアップでは、クラウドプロバイダにオブジェクトストレージのコストを支払います。
+
クラウドにバックアップではソースボリュームの Storage Efficiency が維持されるため、クラウドプロバイダ側で、 data_after_ONTAP 効率化のコストを支払います（重複排除と圧縮が適用されたあとのデータ量が少ないほど）。

* リストア（単一ファイルのリストア）では、クラウドプロバイダに料金が発生するのはインスタンスの実行中のみです。
+
インスタンスは、個々のファイルのリストア時にバックアップスナップショットを参照するためだけに使用されます。コストを節約するために使用していない場合、インスタンスはオフになります。個々のファイルを復元しようとしなかった場合は、まったく展開されません。

+
を参照してください link:task_restore_backups.html#details["導入されている仮想マシン / インスタンスのタイプ"^] サポートされているクラウドプロバイダごとに、



* サービス料金 *

バックアップサービスの料金はネットアップに支払われ、バックアップの作成時のバックアップとリストア時のボリューム、またはファイルに対する費用の両方が含まれます。お客様は、保護対象のデータについてのみ料金を支払うことになります。この料金は、ターゲットバックアップの容量である _Before_ONTAP の効率性で計算されます。

バックアップサービスの料金を支払う方法は 2 つあります。1 つ目の方法はサービスプロバイダから登録することです。サービスプロバイダを利用すると、バックアップデータの量に基づいて月単位の料金を支払うことができます。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。を参照してください <<Licensing,ライセンス>> 詳細については、を参照してください



== ライセンス

クラウドへのバックアップには、お客様所有のライセンスを使用（ BYOL ）と従量課金制（ PAYGO ）の 2 つのライセンスオプションがあります。ライセンスをお持ちでない場合は、 30 日間の無償トライアルをご利用いただけます。



=== 無償トライアルをご利用ください

30 日間の無償トライアル版を使用すると、残りの無料試用日数が通知されます。無償トライアルが終了すると、バックアップは作成されなくなります。サービスを引き続き使用するには、サービスに登録するかライセンスを購入する必要があります。

サービスが無効になってもバックアップは削除されません。バックアップを削除しないかぎり、バックアップで使用する容量のオブジェクトストレージのコストは引き続きクラウドプロバイダから請求されます。



=== 従量課金制のサブスクリプション

PAYGO の場合は、オブジェクトストレージのコストについてクラウドプロバイダに支払い、バックアップライセンスのコストについてはネットアップに支払う必要があります。ライセンスコストは、（ ONTAP の Storage Efficiency 機能を使用する前の）ターゲットのバックアップ容量に基づいて決まります。

* AWS https://aws.amazon.com/marketplace/pp/B07QX2QLXX["価格の詳細については、 Cloud Manager Marketplace のサービスを参照してください"^]。
* Azure https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["価格の詳細については、 Cloud Manager Marketplace のサービスを参照してください"^]。
* GCP ： https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project&rif_reserved["価格の詳細については、 Cloud Manager Marketplace のサービスを参照してください"^]




=== お客様所有のライセンスを使用

BYOL は、期間ベース（ 1 年間 / 2 年間 / 3 年間）で容量ベースであり、バックアップされた容量を（ ONTAP Storage Efficiency の前の）論理的なバックアップに基づいて、 1TB 単位で増分されます。ネットアップに料金を支払うことで、このサービスを一定期間（たとえば 1 年）利用でき、最大バックアップ容量である 10TB にした場合、オブジェクトストレージのコストについてクラウドプロバイダの支払いが必要になります。このサービスを有効にするために、 Cloud Manager のライセンスページに入力するシリアル番号が表示されます。いずれかの制限に達すると、ライセンスを更新する必要があります。を参照してください link:task_managing_licenses.html#adding-and-updating-your-backup-byol-license["バックアップ BYOL ライセンスを追加および更新する"^]。バックアップライセンスはすべての Cloud Volumes ONTAP に適用されます に関連付けられているオンプレミスシステムもサポートします link:concept_cloud_central_accounts.html["Cloud Central アカウント"^]。



==== BYOL ライセンスに関する考慮事項

Backup to Cloud BYOL ライセンスを使用している場合、 Cloud Manager は、バックアップが容量の上限に近づいたときやライセンスの有効期限に近づいたときに通知します。次の通知が表示されます。

* バックアップがライセンスで許可された容量の 80% に達したとき、および制限に達したときに再度実行されます
* ライセンスの有効期限が切れる 30 日前と、ライセンスの有効期限が切れたあとに再度有効になります


これらの通知を受け取った場合は、 Cloud Manager インターフェイスの右下にあるチャットアイコンを使用してライセンスを更新してください。

ライセンスの有効期限が切れると、次の 2 つのことが起こります。

* ONTAP システムに使用しているアカウントにマーケットプレイスアカウントがある場合、バックアップサービスは引き続き実行されますが、 PAYGO ライセンスモデルに切り替えられます。バックアップに使用する容量のバックアップライセンスのコストについては、クラウドプロバイダに課金されます。バックアップに必要なストレージコストについては、ネットアップにお問い合わせください。
* ONTAP システムに使用しているアカウントに Marketplace アカウントがない場合、バックアップサービスは引き続き実行されますが、有効期限に関するメッセージは引き続き送信されます。


BYOL サブスクリプションを更新すると、 Cloud Manager は NetApp から新しいライセンスを自動的に取得してインストールします。Cloud Manager がセキュアなインターネット接続経由でライセンスファイルにアクセスできない場合は、ユーザがファイルを取得して、 Cloud Manager に手動でアップロードできます。手順については、を参照してください link:task_managing_licenses.html#adding-and-updating-your-backup-byol-license["バックアップ BYOL ライセンスを追加および更新する"^]。

PAYGO ライセンスに切り替えられたシステムは、自動的に BYOL ライセンスに戻されます。また、ライセンスなしで実行されていたシステムは警告メッセージの受信を停止し、ライセンスの有効期限が切れている間に実行されたバックアップに対して課金されます。



== クラウドへのバックアップの仕組み

Cloud Volumes ONTAP またはオンプレミスの ONTAP システムでクラウドへのバックアップを有効にすると、サービスはデータのフルバックアップを実行します。ボリューム Snapshot はバックアップイメージに含まれません。初期バックアップ後は、追加のバックアップはすべて差分になります。つまり、変更されたブロックと新しいブロックのみがバックアップされます。



=== バックアップの保管場所バックアップノバショ

バックアップコピーは、 Cloud Manager がクラウドアカウントに作成する S3 バケット、 Azure BLOB コンテナ、または Google Cloud Storage バケットに格納されます。Cloud Volumes ONTAP システムの場合、オブジェクトストアは Cloud Volumes ONTAP システムと同じリージョンに作成されます。オンプレミスの ONTAP システムでは、サービスを有効にするときにリージョンを指定します。

Cloud Volumes ONTAP システムまたはオンプレミスの ONTAP システムごとに 1 つのオブジェクトストアがあります。Cloud Manager は、次のようにオブジェクトストア名を指定します。 NetApp-backup- _clusteruuid_

このオブジェクトストアは削除しないでください。

注：

* AWS では、 Cloud Manager によってが有効になります https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html["Amazon S3 ブロックのパブリックアクセス機能"^] を S3 バケットに配置します。
* Azure では、 Cloud Manager は BLOB コンテナのストレージアカウントを持つ新規または既存のリソースグループを使用します。
* GCP では、 Cloud Manager は Google Cloud Storage バケット用のストレージアカウントを持つ新規または既存のプロジェクトを使用します。




=== サポートされるストレージクラスまたはアクセス階層

* Amazon S3 では、バックアップは _Standard_storage クラスから開始し、 30 日後に _Standard-Infrequent Access_storage クラスに移行します。
* Azure では、バックアップは _COOL アクセス層に関連付けられます。
* GCP では、バックアップはデフォルトで _Standard_storage クラスに関連付けられています。
+
また、 lower cost_Nearline_storage クラスまたは _Coldline_or_Archive_storage クラスを使用することもできます。Google のトピックを参照してください link:https://cloud.google.com/storage/docs/storage-classes["ストレージクラス"^] ストレージクラスの変更については、を参照してください。





=== バックアップ設定はシステム全体に適用されます

クラウドへのバックアップを有効にすると、システムで指定したすべてのボリュームがクラウドにバックアップされます。

保持するバックアップのスケジュールと数はシステムレベルで定義されます。バックアップ設定は、システム上のすべてのボリュームに適用されます。



=== スケジュールは、 daily 、 weekly 、 monthly 、またはその組み合わせです

すべてのボリュームについて、日単位、週単位、または月単位のバックアップを選択できます。また、システム定義のポリシーの中から、 3 カ月、 1 年、 7 年のバックアップと保持を提供するポリシーを選択することもできます。ポリシーは次のとおりです。

[cols="30,20,20,20,30"]
|===
| バックアップポリシー名 3+| 間隔ごとのバックアップ ... | 最大バックアップ 


|  | * 毎日 * | * 毎週 * | * 毎月 * |  


| Netapp3MonthsRetention | 30 | 13 | 3. | 46 


| Netapp1YearRetention | 30 | 13 | 12. | 55 


| ネッパ7YearsRetention | 30 | 53 | 84 | 167 
|===
ONTAP System Manager または ONTAP CLI を使用してシステムに作成したバックアップ保護ポリシーも選択可能です。

カテゴリまたは間隔のバックアップの最大数に達すると、古いバックアップは削除されるため、常に最新のバックアップが保持されます。

データ保護ボリュームのバックアップの保持期間は、ソースの SnapMirror 関係の定義と同じになります。API を使用して必要に応じてこの値を変更できます。



=== バックアップは午前 0 時に作成されます

* 日次バックアップは、毎日午前 0 時を過ぎた直後に開始されます。
* 週次バックアップは、日曜日の朝の午前 0 時を過ぎた直後に開始されます
* 月単位のバックアップは、毎月 1 日の午前 0 時を過ぎた直後に開始されます。


この時点では、ユーザーが指定した時刻にバックアップ操作をスケジュールすることはできません。



=== バックアップコピーは Cloud Central アカウントに関連付けられます

バックアップコピーはに関連付けられます link:concept_cloud_central_accounts.html["Cloud Central アカウント"^] Cloud Manager が配置されます。

同じ Cloud Central アカウントに複数の Cloud Manager システムがある場合、各 Cloud Manager システムには同じバックアップのリストが表示されます。これには、他の Cloud Manager システムの Cloud Volumes ONTAP インスタンスとオンプレミス ONTAP インスタンスに関連付けられたバックアップが含まれます。



== サポートされるボリューム

クラウドへのバックアップでは、 FlexVol の読み書き可能ボリュームとデータ保護（ DP ）ボリュームがサポートされます。

FlexGroup ボリュームと SnapLock ボリュームは現在サポートされていません。



== 制限

* オンプレミスの ONTAP システムからバックアップを作成する場合は、 Cloud Manager をクラウド（ Azure または AWS ）に導入する必要があります。オンプレミスの Cloud Manager 環境はサポートされていません。
* DP ボリュームをバックアップする場合は、ソースボリュームの SnapMirror ポリシーに定義されたルールで、「毎日」、「毎週」、または「毎月」の「クラウドへのバックアップ」ポリシー名に一致するラベルを使用する必要があります。そうしないと、その DP ボリュームのバックアップは失敗します。
* Azure では、 Cloud Volumes ONTAP の導入時にクラウドへのバックアップを有効にした場合、 Cloud Manager によってリソースグループが作成されます。このリソースグループは変更できません。クラウドへのバックアップを有効にする際に独自のリソースグループを選択する場合は、 Cloud Volumes ONTAP を導入する際に * クラウドへのバックアップを無効にしてから、クラウドへのバックアップを有効にして、クラウドへのバックアップ設定ページからリソースグループを選択します。
* Cloud Volumes ONTAP システムからボリュームをバックアップする場合、 Cloud Manager 以外で作成したボリュームは自動ではバックアップされません。たとえば、 ONTAP CLI 、 ONTAP API 、または System Manager からボリュームを作成した場合、そのボリュームは自動的にはバックアップされません。これらのボリュームをバックアップするには、クラウドへのバックアップを無効にしてから再度有効にする必要があります。
* オブジェクトストレージからの ILM （階層化）、 AWS Glacier または同等の下位階層のオブジェクトストレージへの直接書き込みはサポートされていません。
* SVM-DR 構成と SM-BC 構成はサポートされません。
* MetroCluster （ MCC ）バックアップは、 ONTAP セカンダリからのみサポートされます。 MCC-> SnapMirror -> ONTAP -> Cloud Backup Service -> オブジェクトストレージ。
* オブジェクトストアでの Worm/Compliance モードはサポートされません。




=== 単一ファイルのリストアに関する制限事項

* 単一ファイルのリストアでは、個々のファイルをリストアできます。現在、フォルダ / ディレクトリのリストアはサポートされていません。
* Cloud Volumes ONTAP システムまたはオンプレミスシステムでは、 ONTAP のバージョンが 9.6 以降である必要があります。
* クロスアカウントリストアを実行するには、クラウドプロバイダコンソールで手動の操作が必要です。AWS のトピックを参照してください https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example2.html["クロスアカウントバケットの権限を付与しています"^] を参照してください。
* サポートされていない構成：
+
** 現在、 Gov Cloud はサポートされていません。
** 異なるサブネット内の異なる Cloud Manager を使用する同じアカウント。


* リストアでは、最大 30,000 個のフラットファイルを含む 1 つのディレクトリを参照できます。これよりも大きなディレクトリは現在サポートされていません。

