---
sidebar: sidebar 
permalink: concept_write_speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: Cloud Manager では、 Cloud Volumes ONTAP に対して通常または高速の書き込み速度を選択できます。書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。 
---
= 書き込み速度
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager では、 Cloud Volumes ONTAP に対して通常または高速の書き込み速度を選択できます。書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。

高速の書き込み速度は、すべてのタイプのシングルノードシステムでサポートされています。特定のインスタンスまたは VM タイプを使用している場合は、 AWS と Azure の HA ペアでもサポートされます（サポートされるインスタンスと VM タイプの一覧については、以下のセクションを参照してください）。GCP の HA ペアでは、高速の書き込み速度はサポートされていません。



== 通常の書き込み速度

通常の書き込み速度を選択した場合、データはディスクに直接書き込まれます。データをディスクに直接書き込んだ場合、計画外のシステム停止が発生した場合や、計画外のシステム停止が発生した場合のデータ損失の可能性を低減します（ HA ペアのみ）。

デフォルトでは、通常の書き込み速度が使用されます。



== 高速の書き込み速度

高速書き込みを選択すると、データはディスクに書き込まれる前にメモリにバッファされるため、書き込みパフォーマンスが向上します。このキャッシュにより、計画外のシステム停止が発生した場合にデータが失われる可能性があります。

計画外のシステム停止が発生した場合に失われる可能性があるデータの量は、最後の 2 つの整合ポイントの範囲です。整合ポイントとは、バッファされたデータをディスクに書き込むことです。整合ポイントは、書き込みログがいっぱいになったとき、または 10 秒後（どちらか早い方）に発生します。ただし、クラウドプロバイダが提供するストレージのパフォーマンスが整合ポイントの処理時間に影響する可能性があります。



=== 高速書き込みを使用する場合

高速の書き込みパフォーマンスが求められるワークロードで、計画外のシステム停止が発生した場合や、計画外のシステム停止（ HA ペアのみ）が伴うカスケード障害が発生した場合のデータ損失リスクに対処できる場合は、高速の書き込み速度を使用することを推奨します。



=== 高速書き込みを使用する場合の推奨事項

高速の書き込み速度を有効にする場合は、アプリケーションレイヤでの書き込み保護を確保するか、またはデータ損失が発生した場合にアプリケーションで許容されるようにする必要があります。



=== 高速の書き込み速度をサポートする構成

すべての Cloud Volumes ONTAP 構成で高速書き込みがサポートされるわけではありません。デフォルトでは、これらの構成では通常の書き込み速度が使用されます。



==== AWS

シングルノードシステムを使用する場合、 Cloud Volumes ONTAP では、すべてのインスタンスタイプで高速な書き込み速度がサポートされます。

HA ペアを使用する場合、 Cloud Volumes ONTAP では 9.8 リリース以降、次の種類のインスタンスで高速の書き込み速度がサポートされます。

* c5.9xlarge のサイズ
* c5.18 × ラージ
* c5d.csi
* c5d.9xlarge
* c5d.18 x ラージ
* c5n.9xlarge
* c5n.18 × ラージ
* m5.2xlarge
* m5.mc
* m5.16 x ラージ
* m5d.8xlarge
* m5d.12xlarge
* m5n.2xlarge
* r5.2xlarge
* r5.8xlarge
* r5.12xlarge
* r5d.2xlarge




==== Azure

シングルノードシステムを使用する場合、 Cloud Volumes ONTAP では、すべての種類の VM で高速な書き込み速度がサポートされます。

HA ペアを使用する場合、 Cloud Volumes ONTAP では 9.8 リリース以降、次の種類の VM で高速の書き込み速度がサポートされます。

* DS5_v2 の場合
* DS14_v2
* DS15_v2 の場合
* E48s_v3




==== Google Cloud

シングルノードシステムを使用する場合、 Cloud Volumes ONTAP では、すべての種類のマシンで高速な書き込み速度がサポートされます。

Cloud Volumes ONTAP では、 Google Cloud の HA ペアでの高速書き込みはサポートされていません。



== 書き込み速度を選択する方法

を作成するときに、書き込み速度を選択できます 新しい作業環境を構築できます link:task_modifying_ontap_cloud.html#changing-write-speed-to-normal-or-high.html["既存のシステムの書き込み速度を変更する"]。



== データ損失が発生した場合の予測

高速の書き込み速度を選択し、データ損失が発生した場合、システムをブートして、ユーザの手を煩わせることなくデータを提供できるはずです。ノードでデータが失われると、 2 つの EMS メッセージが報告されます。1 つは wafl.root.content.changed で、もう 1 つは ERROR 重大度レベルイベントです。もう 1 つは、デバッグ重大度レベルイベントを含む nv.check.failed です。両方のメッセージがデータ損失の兆候として存在している必要があります。



== データ損失が発生した場合のデータアクセスの停止方法

データ損失について懸念がある場合、データ損失時にアプリケーションの実行を停止し、データ損失の問題に適切に対処したあとでデータアクセスを再開するには、 CLI から NVFAIL オプションを使用してこの目標を達成します。

をクリックして NVFAIL オプションを有効にします:: vol modify -volume <vol-name> -nvfail on `
をクリックして NVFAIL 設定を確認します:: vol show -volume <vol-name> -fields nvfail`
NVFAIL オプションを無効にする場合:: vol modify -volume <vol-name> -nvfail off `


データ損失が発生した場合、 NVFAIL が有効になっている NFS または iSCSI ボリュームは、データ処理を停止する必要があります（ステートレスプロトコルである CIFS への影響はありません）。詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["NFS ボリュームまたは LUN へのアクセスに対する NVFAIL の影響"^]。

をクリックして NVFAIL 状態を確認します:: vol show -fields in in-nvfailed-state 」を参照してください


データ損失の問題に適切に対処したら、 NVFAIL 状態を解消でき、ボリュームへのデータアクセスが可能になります。

をクリックして NVFAIL 状態を解消します:: vol modify -volume <vol-name> -in-nvfailed-state false

