---
sidebar: sidebar 
permalink: concept_replication.html 
keywords: ontap, cluster, discover, manage, cloud manager, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention 
summary: NetApp SnapMirror は、 LAN または WAN 経由でデータを高速でレプリケートするため、仮想環境と従来の環境の両方で、高いデータ可用性と高速なデータレプリケーションを実現できます。ネットアップストレージシステムにデータをレプリケートし、セカンダリデータを継続的に更新することで、データを最新の状態に保ちながら、必要なときにいつでもデータを利用できるようになります。外部レプリケーションサーバは必要ありません。 
---
= レプリケーションサービスについて説明します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror は、 LAN または WAN 経由でデータを高速でレプリケートするため、仮想環境と従来の環境の両方で、高いデータ可用性と高速なデータレプリケーションを実現できます。ネットアップストレージシステムにデータをレプリケートし、セカンダリデータを継続的に更新することで、データを最新の状態に保ちながら、必要なときにいつでもデータを利用できるようになります。外部レプリケーションサーバは必要ありません。



== の機能

* ストレージシステム間でデータをレプリケートして、クラウドまたはクラウド間でバックアップとディザスタリカバリをサポートします。
* 高い可用性を備えた信頼性の高い DR 環境を実現します。
* ONTAP ストレージ間の効率的なブロックレベルのレプリケーションは高速かつ効率的で、 DR とバックアップの両方をきめ細かくリカバリできます。




== コスト

ネットアップでは、レプリケーションサービスの使用料は発生しませんが、データの入力と出力に該当する料金がクラウドプロバイダにあるかどうかを確認する必要があります。



== サポートされている作業環境

Cloud Manager では、次のタイプの作業環境間でデータレプリケーションを実行できます。

* Cloud Volumes ONTAP システムから別の Cloud Volumes に移行する ONTAP システム
* Cloud Volumes ONTAP システムとオンプレミス ONTAP の間 クラスタ
* オンプレミスの ONTAP クラスタから別のオンプレミスの ONTAP クラスタへ




== データレプリケーションの仕組み

Cloud Manager では、 SnapMirror と SnapVault テクノロジを使用して、別々のシステム上のボリューム間でのデータレプリケーションを簡素化します。ソースボリュームとデスティネーションボリュームを特定し、レプリケーションポリシーとスケジュールを選択するだけで済みます。Cloud Manager が Cloud Volumes ONTAP に必要なディスクを購入し、関係を設定してレプリケーションポリシーを適用したあと、ボリューム間のベースライン転送を開始します。


NOTE: ベースライン転送には、ソースデータのフルコピーが含まれます。その後の転送には、ソースデータの差分コピーが含まれます。



== サポートされるデータ保護構成

Cloud Manager は、シンプルなファンアウト / カスケードデータ保護構成をサポートしています。

* シンプルな構成では、ボリューム A からボリューム B へのレプリケーションが行われます
* ファンアウト構成では、ボリューム A から複数のデスティネーションへのレプリケーションが行われます。
* カスケード構成では、レプリケーションはボリューム A からボリューム B 、およびボリューム B からボリューム C に行われます

