---
sidebar: sidebar 
permalink: reference_aws_support.html 
keywords: aws, amazon, s3, support, regions, storage classes 
summary: Cloud Tiering は、複数の S3 ストレージクラスとほとんどのリージョンをサポートしています。 
---
= サポートされている S3 ストレージクラスとリージョン
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Tiering は、複数の S3 ストレージクラスとほとんどのリージョンをサポートしています。



== サポートされている S3 ストレージクラス

AWS へのデータ階層化を設定すると、 Cloud Tiering は、アクセス頻度の低いデータに _Standard_storage クラスを自動的に使用します。Cloud Tiering では、ライフサイクルルールを適用して、特定の日数が経過したデータを _Standard_storage クラスから別のストレージクラスに移行できます。次のストレージクラスから選択できます。

* 標準的なアクセス頻度は低い
* 1 ゾーン -IA
* インテリジェントな階層化（ AWS が頻繁なアクセスとアクセス頻度の低いアクセスでアクセスパターンが変化したときに自動的に 2 つの階層間でデータを移動）


別のストレージクラスを選択しない場合、データは _Standard_storage クラスに残り、ルールは適用されません。

クラウド階層化ライフサイクルルールを設定する場合は、 AWS アカウントでバケットをセットアップするときにライフサイクルルールを設定しないでください。

https://aws.amazon.com/s3/storage-classes/["S3 ストレージクラスについて説明します"^]。



== サポートされている AWS リージョン

Cloud Tiering は、次の AWS リージョンをサポートしています。



==== アジア太平洋地域

* ムンバイ
* ソウル
* シンガポール
* シドニー
* 東京




==== ヨーロッパ

* フランクフルト
* アイルランド
* ロンドン
* パリ
* ストッケホルム




==== 北米

* カナダセントラル
* GovCloud （ US-West ）– ONTAP 9.3 以降
* 米国東部（ N（バージニア州）
* 米国東部（オハイオ州）
* US West （ Nカリフォルニア）
* US West （オレゴン州）




==== 南米

* サンパウロ

