---
sidebar: sidebar 
permalink: reference_limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, cloud manager, Cloud Volumes ONTAP, days, 14 days, running, Connectors should remain running 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください



== 従量課金制の Azure と Google Cloud のパートナーは利用できません

Microsoft Cloud 解決策 Provider （ CSP ）パートナー様または Google Cloud パートナー様は、従量課金制のサブスクリプションをご利用いただけません。ライセンスを購入し、 BYOL ライセンスを使用した NetApp クラウドソリューションを導入する必要があります。

従量課金制のサブスクリプションは、次の NetApp クラウドサービスでは利用できません。

* Cloud Volumes ONTAP Explore 、 Standard 、または Premium
* Cloud Tiering Service の略
* Cloud Backup サービスの略
* クラウドデータの意味




== Azure リソースグループには HA ペアが 1 つしかありません

Azure に導入する Cloud Volumes ONTAP HA ペアごとに専用のリソースグループを使用する必要があります。リソースグループでサポートされる HA ペアは 1 つだけです。

Azure リソースグループに 2 つ目の Cloud Volumes ONTAP HA ペアを導入しようとすると、 Cloud Manager で接続の問題が発生します。



== コネクタは動作したままにしてください

コネクタは常時稼働している必要があります。有効にするサービスの継続的な健常性と運用性にとって重要です。

たとえば、 Cloud Volumes ONTAP PAYGO システムの正常性と運用においては、コネクタが重要な要素です。コネクタの電源がオフの場合、 Cloud Volumes ONTAP PAYGO システムは、コネクタとの通信を 14 日以上失った後にシャットダウンします。



== 政府機関では SaaS プラットフォームが無効になっています

コネクタを AWS GovCloud リージョン、 Azure Government リージョン、または Azure DoD リージョンに導入した場合、 Cloud Manager へのアクセスはコネクタのホスト IP アドレスからのみ可能です。SaaS プラットフォームへのアクセスは、アカウント全体で無効になります。

つまり、エンドユーザの内部 VPC / VNet にアクセスできる特権ユーザのみが Cloud Manager の UI または API を使用できます。

また、次のサービスが Cloud Manager から利用できないことも意味します。

* クラウドデータの意味
* Kubernetes
* クラウド階層化
* グローバルファイルキャッシュ


これらのサービスを使用するには、 SaaS プラットフォームが必要です。


NOTE: 監視サービスは政府機関でサポートされており、利用できます。



== Cloud Manager では、 Cloud Volumes ONTAP のダウングレードはサポートされていません

Cloud Manager では、 Cloud Volumes ONTAP を以前のバージョンにダウングレードすることはできません。ダウングレードについては、ネットアップテクニカルサポートにお問い合わせください。



== 共有 Linux ホストはサポートされません

コネクタは、他のアプリケーションと共有されているホストではサポートされていません。専用のホストである必要があります。



== Cloud Manager は FlexGroup ボリュームをサポートしていません

Cloud Volumes ONTAP では FlexGroup ボリュームがサポートされますが、 Cloud Manager ではサポートされません。System Manager または CLI から FlexGroup ボリュームを作成する場合は、 Cloud Manager の容量管理モードを手動に設定する必要があります。FlexGroup ボリュームで自動モードが適切に機能しない可能性があります。



== Cloud Manager は ONTAP S3 をサポートしていません

Azure の Cloud Volumes ONTAP は S3 を使用するオブジェクトをサポートしていますが、 Cloud Manager はこの機能の管理機能を提供しません。CLI を使用することが、 Cloud Volumes ONTAP からの S3 クライアントアクセスを設定するためのベストプラクティスです。詳細については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 構成パワーガイド"^]。
