---
sidebar: sidebar 
permalink: reference_private_data_categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Cloud Data Sense がボリューム、 Amazon S3 バケット、データベース内で識別できるプライベートデータには、さまざまな種類があります。以下のカテゴリを参照してください。 
---
= プライベートデータのカテゴリ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Data Sense がボリューム、 Amazon S3 バケット、データベース、 OneDrive フォルダ内で識別できるプライベートデータには、さまざまな種類があります。以下のカテゴリを参照してください。


TIP: その他の国の ID 番号や医療機関の ID など、プライベートデータの種類を識別するためにクラウドデータセンスが必要な場合は、 ng-contact-data-sense@netapp.com にリクエストを送信してください。



== 個人データの種類

ファイルに含まれる個人データは、一般的な個人データまたは国 ID です。3 番目の列は、 Cloud Data Sense で使用されているかどうかを示します link:task_controlling_private_data.html#personal-data["近接性検証"^] 識別子の調査結果を検証します。

データベースサーバーをスキャンする場合は、ファイル内にある個人データのリストに追加できます。Data Fusion 機能を使用すると、データベーステーブルの列を選択して、クラウドデータ検出でスキャンで検索する追加の識別子を選択できます。を参照してください link:task_managing_data_fusion.html["Data Fusion を使用して個人データ識別子を追加する"^] を参照してください。

[cols="20,50,18"]
|===
| を入力します | 識別子 | 近接性検証： 


.4+| 全般 | E メールアドレス | いいえ 


| クレジットカード番号 | いいえ 


| IBAN 番号（国際銀行口座番号） | いいえ 


| IP アドレス | いいえ 


.32+| 国家識別番号 | オーストリア SSN | はい。 


| ベルギー ID （ Numero National ） | はい。 


| ブラジル ID （ CPF ） | はい。 


| ブルガリア語 ID （ UCN ） | はい。 


| カリフォルニア州の運転免許証 | はい。 


| クロアチア ID （ OIB ） | はい。 


| キプロス税識別番号（ TIC ） | はい。 


| チェコ語 / スロバキア語 ID | はい。 


| デンマーク語 ID （ CPR ） | はい。 


| オランダ語 ID （ BSN ） | はい。 


| エストニア ID | はい。 


| フィンランド ID （ HETU ） | はい。 


| フランス税識別番号（ SPI ） | はい。 


| ドイツの納税者番号（ Steuerliche Identifyikationsnummer ） | はい。 


| ギリシャ ID | はい。 


| ハンガリー語税識別番号 | はい。 


| アイルランド ID （ PPS ） | はい。 


| イスラエルの身分証明書 | はい。 


| イタリアの税識別番号 | はい。 


| ラトビア ID | はい。 


| リトアニア ID | はい。 


| ルクセンブルク iD | はい。 


| マルタ ID | はい。 


| ポーランド ID （ PESEL ） | はい。 


| ポルトガル語税識別番号（ NIF ） | はい。 


| ルーマニア語 ID （ CNP ） | はい。 


| スロベニア語 ID （ EMSO ） | はい。 


| 南アフリカ ID | はい。 


| スペイン語税識別番号 | はい。 


| スウェーデン語 ID | はい。 


| 英国ID （ニーノ） | はい。 


| 米国社会保障番号（ SSN ） | はい。 
|===


== 機密性の高い個人データのタイプ

Cloud Data Sense がファイル内で検出できる機密性の高い個人データには、次のものがあります。

刑事手続きの参照:: 天然人の犯罪に関するデータ。
『民族リファレンス』を参照してください:: 自然な人の人種または民族の起源に関するデータ。
健全性リファレンス:: 自然な人の健康に関するデータ。
ICD-9-CM Medical Codes:: 医療および医療業界で使用されるコード。
ICD-10-CM Medical Codes:: 医療および医療業界で使用されるコード。
哲学の信仰の参照:: 自然な人の哲学的信念に関するデータ。
政治的見解参照:: 自然な人の政治的意見に関するデータ。
宗教的信条参照:: 自然な人の宗教的信条に関するデータ。
性別生命または方向の参照:: 自然人の性生活や性的指向に関するデータ。




== カテゴリのタイプ

Cloud Data Sense は、次のようにデータを分類します。

財務::
+
--
* 貸借対照表
* 注文書
* 請求書
* 四半期ごとのレポート


--
時間::
+
--
* バックグラウンドチェック
* 報酬プラン
* 従業員の契約
* 従業員レビュー
* 健常性
* 再開します


--
法律::
+
--
* NDAS
* ベンダー - お客様との契約


--
マーケティング::
+
--
* キャンペーン
* 会議


--
処理::
+
--
* 監査レポート


--
営業::
+
--
* SO 番号


--
サービス::
+
--
* RFI （ RFI ）
* RFP
* SOW の作成
* トレーニング


--
サポート::
+
--
* 苦情やチケット


--
メタデータのカテゴリ::
+
--
* アプリケーションデータ
* アーカイブファイル
* 音声
* ビジネスアプリケーションデータ
* CAD ファイル
* コード
* データベースおよびインデックス・ファイル
* デザインファイル（ Design Files ）
* E メールアプリケーションデータ
* 実行可能ファイル
* 財務アプリケーションデータ
* ヘルスアプリケーションデータ
* イメージ
* ログ
* その他の文書
* その他のプレゼンテーション
* その他のスプレッドシート
* ビデオ


--




== ファイルのタイプ

Cloud Data Sense は、すべてのファイルをスキャンしてカテゴリやメタデータに関する分析情報を検索し、ダッシュボードのファイルタイプセクションにすべてのファイルタイプを表示します。

しかし、データセンスが個人識別情報（ PII ）を検出した場合、または dsar 検索を実行した場合は、 .csv 、 .dcm 、 .dcm 、 .dom 、 .DOC 、 .DOCX というファイル形式のみがサポートされます。 .json 、 .pdf 、 .PPTX 、 .rtf 、 .TXT 、 .XLS 、 .xlsx のいずれかです。



== 見つかった情報の正確性

ネットアップでは、 Cloud Data Sense が特定した個人データと機密性の高い個人データの正確性を 100% 保証することはできません。必ずデータを確認して情報を検証してください。

以下の表は、テストに基づいて、データ検出によって検出された情報の正確さを示しています。精度 _ と _ リコール _ で分解します。

精度（ Precision ）:: 検出されたデータが正しく識別された確率。たとえば、個人データの正確な割合が 90% の場合、個人情報を含むと識別された 10 個中 9 個のファイルに個人情報が実際に含まれていることを意味します。10 個のファイルのうち 1 個はフォールスポジティブです。
取り消し:: データが持つべきものを見つける確率。たとえば、個人データのリコール率が 70% の場合、データセンスは、実際に個人情報を含む 10 個のファイルのうち 7 個を識別できます。データセンスは、データの 30% を見逃すことになり、ダッシュボードには表示されません。


私たちは、常に結果の正確さを改善しています。これらの改善は、今後の Data Sense リリースで自動的に利用できるようになる予定です。

[cols="25,20,20"]
|===
| を入力します | 精度（ Precision ） | 取り消し 


| 個人データ - 一般 | 90% ~ 95% | 60% ～ 80% 


| 個人データ - 国 ID | 30% ~ 60% | 40% ~ 60% 


| 機密性の高い個人データ | 80% ~ 95% | 20% ~ 30% 


| カテゴリ | 90% ~ 97% | 60% ～ 80% 
|===