name: Repo Sync

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: https://${{ secrets.GH_TOKEN }}@github.com/NetAppDocs/${{ secrets.SOURCE_REPO }}.git
        source_branch: main
        destination_branch: ${{ secrets.REPO_SYNC_BRANCH }}
        github_token: ${{ secrets.GH_TOKEN }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: ${{ secrets.REPO_SYNC_BRANCH }}
        destination_branch: main
        github_token: ${{ secrets.GH_TOKEN }}
        pr_title: "Sync main with ${{ secrets.SOURCE_REPO }}"
